---
- name: install HAProxy
    yum:
      name: haproxy
      state: latest
  package: name=haproxy state=present

- name: enable HAProxy
    service:
      name: haproxy
      state: started

- name: configure haproxy
    template:
      src: ./haproxy.cfg.j2
      dest: /etc/haproxy/haproxy.cfg
      mode: 0644
      validate: haproxy -f %s -c -q
  notify: restart haproxy

- name: Ensure HAProxy is started and enabled on boot.
    service: 
      name: haproxy
      state: started
      enabled: yes
